---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lancie-frontend-beta
  namespace: lancie
  labels:
    app: lancie-frontend-beta
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: lancie-frontend-beta
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: lancie-frontend-beta
      labels:
        app: lancie-frontend-beta
    spec:
      containers:
      - name: lancie-frontend-beta
        image: quay.io/areafiftylan/lancie-frontend-beta:2832
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: "500m"
            memory: 64Mi
