---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcod
  namespace: w3cie
  labels:
    k8s-app: mcod
  annotations:
    fluxcd.io/automated: 'true'
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      k8s-app: mcod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: mcod
      labels:
        k8s-app: mcod
    spec:
      containers:
      - name: mcod
        image: quay.io/wisvch/mcod:55
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        volumeMounts:
        - mountPath: /tmp
          name: tmpfs
      restartPolicy: Always
      volumes:
      - emptyDir:
          medium: Memory
        name: tmpfs
