apiVersion: v1
kind: Service
metadata:
  name: member-registration
  namespace: w3cie
  labels:
    app: member-registration
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app: member-registration
  sessionAffinity: None
  type: ClusterIP
