apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vsphere
parameters:
  diskformat: zeroedthick
  fstype: xfs
provisioner: kubernetes.io/vsphere-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
