apiVersion: v1
kind: Service
metadata:
  name: datadog-agent
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: apm
    port: 8126
    targetPort: 8126
    protocol: TCP
  selector:
    app: datadog-agent
