apiVersion: v1
kind: Service
metadata:
  labels:
    app: hackdelft-2022
  name: hackdelft-2022
  namespace: hackdelft
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: hackdelft-2022
  sessionAffinity: None
  type: ClusterIP
